const MARKERS_LIST = {
    LOAD_REQUESTED: 'MARKERS_LIST.LOAD_REQUESTED',
    LOAD_FAILED: 'MARKERS_LIST.LOAD_FAILED',
    LIST_RECEIVED: 'MARKERS_LIST.LIST_RECEIVED'
}

const MARKERS_ADD = {
    ADD_REQUESTED: 'MARKERS_ADD.ADD_REQUESTED',
    ADD_FAILED: 'MARKERS_ADD.ADD_FAILED',
    ADD_SUCCEEDED: 'MARKERS_ADD.ADD_SUCCEEDED'
}

const MARKERS_UPDATE = {
    UPDATE_REQUESTED: 'MARKERS_UPDATE.UPDATE_REQUESTED',
    UPDATE_FAILED: 'MARKERS_UPDATE.UPDATE_FAILED',
    UPDATE_SUCCEEDED: 'MARKERS_UPDATE.UPDATE_SUCCEEDED'
}

const MARKERS_REMOVE = {
    REMVOE_REQUESTED: 'MARKERS_REMOVE.REMVOE_REQUESTED',
    REMOVE_FAILED: 'MARKERS_REMOVE.REMOVE_FAILED',
    REMOVE_SUCCEEDED: 'MARKERS_REMOVE.REMOVE_SUCCEEDED'
}

export default {
    MARKERS_LIST,
    MARKERS_ADD,
    MARKERS_UPDATE,
    MARKERS_REMOVE
}